language: node_js
node_js:
  - lts/*

deploy:
  provider: firebase
  project: $PROJECT_ID
  token:
    secure: $FIREBASE_TOKEN
  skip_cleanup: true
  on:
    tags: true

script:
  - yarn lint
  - yarn build
  - cd functions
  - npm install
