language: node_js
node_js:
  - lts/*

deploy:
  provider: firebase
  project: $PROJECT_ID
  token:
    secure: $FIREBASE_TOKEN
  skip_cleanup: true

script:
  - cd functions
  - npm install
  - ../
  - yarn lint
  - yarn build
